[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "inox2d"
version = "0.3.0"
description = "Python bindings for Inox2D"
requires-python = ">=3.8"
dependencies = []

[tool.maturin]
features = ["pyo3/extension-module"]
module-name = "inox2d"
